<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Fintrox.Modules.Projects.Application/Fintrox.Modules.Projects.Application.csproj" />
    <ProjectReference Include="../Fintrox.Modules.Projects.Domain/Fintrox.Modules.Projects.Domain.csproj" />
    <ProjectReference Include="../Fintrox.Modules.Projects.Contracts/Fintrox.Modules.Projects.Contracts.csproj" />
  </ItemGroup>
</Project>
