<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Fintrox.Modules.Integrations.Application/Fintrox.Modules.Integrations.Application.csproj" />
    <ProjectReference Include="../Fintrox.Modules.Integrations.Contracts/Fintrox.Modules.Integrations.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
