<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Fintrox.Modules.WarehouseManagement.Domain/Fintrox.Modules.WarehouseManagement.Domain.csproj" />
    <ProjectReference Include="../Fintrox.Modules.WarehouseManagement.Contracts/Fintrox.Modules.WarehouseManagement.Contracts.csproj" />
  </ItemGroup>
</Project>
