<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Fintrox.Modules.Manufacturing.Application/Fintrox.Modules.Manufacturing.Application.csproj" />
    <ProjectReference Include="../Fintrox.Modules.Manufacturing.Domain/Fintrox.Modules.Manufacturing.Domain.csproj" />
    <ProjectReference Include="../Fintrox.Modules.Manufacturing.Contracts/Fintrox.Modules.Manufacturing.Contracts.csproj" />
  </ItemGroup>
</Project>
